version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # UI に保管されている ID・パスワードを使い
     # プライベート Docker イメージによる専用 DB を稼働させる
     - run: |
         sh exec.sh
         num=$(grep line result.txt | wc -l)
         echo $num
        # if [ $num -eq 0 ]; then
        #   exit 0
        # else
        #   exit 1
        # fi
