version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # UI に保管されている ID・パスワードを使い
     # プライベート Docker イメージによる専用 DB を稼働させる
     - run: |
         docker run --rm -v "$PWD":/home/ninerules tamada/9rules:latest A
